map_size: 7
p: 0.9
is_slippery: True
training_steps: 5000
eval_steps: 5
runs: 10
output_path: "results"
splits:
  - 0.50
combinations:
  - algorithm: qlearning
    exploration: epsilon_greedy
  - algorithm: qlearning
    exploration: softmax
  - algorithm: sarsa
    exploration: epsilon_greedy
  - algorithm: sarsa
    exploration: softmax
